### PR TITLE
Enable util.promisify(appkit.terminal.question)

### PR DESCRIPTION
**Pull request by mikefelix**

### CODE REVIEW

**Comment by trevorlinton** [comment]
Also, you'll need to bump the version in package.json for it to be seen by with aka update, i'll add you to the npmjs.org account so you can publish up the new version.

**Comment by trevorlinton** [comment]
Also also, what's your npmjs.org account name?

**Comment by mikefelix** [comment]
mfelix

**Comment by trevorlinton** [comment]
@mikefelix i added you as a maintainer on npm, once logged in via npm run `npm publish` to push up the new version.

**Pull request merged**
